### ISSUE TITLE
some problem about the flask version

### ISSUE THREAD

**Issue by ReverseSystem001** [cavalleria/cavaface.pytorch#24]
Hi, can you provide the flask version. when I run the evaluate_server.py it reports:
Traceback (most recent call last):
  File "evaluate_service.py", line 12, in <module>
    import flask
  File "/usr/local/lib64/python3.6/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 69, in <module>
    from .wrappers import Request
  File "/usr/local/lib64/python3.6/site-packages/flask/wrappers.py", line 14, in <module>
    from werkzeug.wrappers.json import JSONMixin as _JSONMixin
ModuleNotFoundError: No module named 'werkzeug.wrappers.json'; 'werkzeug.wrappers' is not a package

**Comment by ReverseSystem001** [comment]
When I tried pip3 install flask==1.0.0. it works.thanks
