### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'deprecated'

### ISSUE THREAD

**Issue by Nakupenda-7** [cavalleria/cavaface.pytorch#63]
Traceback (most recent call last):
  File "E:/cavaface.pytorch/train.py", line 23, in <module>
    from apex.parallel import DistributedDataParallel as DDP
  File "E:\anaconda\lib\site-packages\apex\parallel\__init__.py", line 8, in <module>
    ReduceOp = torch.distributed.deprecated.reduce_op
AttributeError: module 'torch.distributed' has no attribute 'deprecated'

**Comment by cavalleria** [comment]
please make sure your env settings

**Comment by Nakupenda-7** [comment]
> please make sure your env settings

Is it because windows does not support?

**Comment by cavalleria** [comment]
i have not tested in windows. maybe

**Comment by cepedus** [comment]
windows does not support DistributedDataParallel nor apex
