### ISSUE TITLE
Model loading error

### ISSUE THREAD

**Issue by Youngboy12** [cavalleria/cavaface.pytorch#71]
When I run bash run.sh for evaluation，there is a error happened：
Traceback (most recent call last):
  File "./main.py", line 179, in <module>
    _main(args)
  File "./main.py", line 68, in _main
    net = _load_model(args)
  File "./main.py", line 31, in _load_model
    net = get_infer(args)
  File "/remote_projects/cavaface/evaluation/infer/__init__.py", line 8, in get_infer
    return CitrusPytorchInfer(args, dtype=dtype)
  File "/remote_projects/cavaface/evaluation/infer/citrus_pytorch_infer.py", line 20, in __init__
    super(CitrusPytorchInfer, self).__init__(args=args, dtype=dtype)
  File "/remote_projects/cavaface/evaluation/infer/citrus_base_infer.py", line 260, in __init__
    self._load_model()
  File "/remote_projects/cavaface/evaluation/infer/citrus_pytorch_infer.py", line 37, in _load_model
    tnet.model=torch.jit.load(spath[0], map_location=tnet.ctx)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 221, in load
    raise ValueError("The provided filename {} does not exist".format(f))
ValueError: The provided filename /workspace/results/lyb_results/IR_SE_100_Arcface/model_ep24_1.pth does not exist

Can you help me about that？

**Comment by cavalleria** [comment]
please set model path properly

**Comment by Youngboy12** [comment]
> please set model path properly

Is this path a local path? Do I need to download the model in advance？Thanks.

**Comment by Youngboy12** [comment]
> please set model path properly

谢谢。我暂时登录不了google云盘，可以提供一下百度云或是其他的路径吗？

**Comment by Youngboy12** [comment]
I got it, Thanks.
